version: '3.8'

services:
  backend:
    build: 
      context: ./backend 
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/app
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - DATABASE_URL=${DATABASE_URL}

  frontend:
    build:
      context: ./frontend 
    ports:
      - "80:80" 
    depends_on:
      - backend 
    environment:
      - REACT_APP_BACKEND_URL=${REACT_APP_BACKEND_URL}
